module-user_interface/webapp/plugins/devices/mako_camera/__init__.py
from .api import bp as api_bp
from .views import bp as views_bp

module-user_interface/webapp/plugins/devices/mako_camera/views.py
import cv2
import threading
from vimba import Vimba
from vimba.feature import FeatureTypes

# from .utils import get_camera, setup_camera, Camera, FrameStatus, Frame, frame_queue, cam_running_event
from .core import mako_camera
from ...utils import load_config, save_config, web_frame_generator

from flask import Blueprint, Response, current_app
from flask import render_template, request, jsonify
import json

from queue import Queue
from threading import Event


bp = Blueprint("mako_camera", __name__, url_prefix="/mako_camera", template_folder="templates")


@bp.route("/get-frame")
def mako_camera_stream():

    config = load_config()
    vimba_config = {}
    if config:
        vimba_config = config.get("plugins", {}).get("devices", {}).get("mako_camera", {})

    return Response(
        web_frame_generator(mako_camera, vimba_config), mimetype="multipart/x-mixed-replace; boundary=frame"
    )


@bp.route("/configure", methods=["GET", "POST"])
def configure():
    if request.method == "POST":
        print(request.form.to_dict())
        failed_features = mako_camera.setup_camera(request.form.to_dict())
        features_list = mako_camera.list_features()
        current_values = {
            feature["name"]: str(feature["value"])
            for feature in features_list
            if "value" in feature and feature["name"] not in failed_features
        }
        current_config = load_config()
        current_config["plugins"]["devices"]["mako_camera"] = current_values
        save_config(current_config)
        if failed_features:
            return render_template(
                "mako_camera/configure_camera.html", cam_features=mako_camera.list_features(), failed_features=failed_features
            )

    mako_camera.cam_running_event.clear()
    return render_template("mako_camera/configure_camera.html", cam_features=mako_camera.list_features())


@bp.route("/config-options")
def get_features():

    features = mako_camera.list_features()
    response = Response(response=json.dumps(features, default=str), status=200, mimetype="application/json")
    return response

module-user_interface/webapp/plugins/devices/mako_camera/templates/mako_camera/configure_camera.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configure Camera</title>
</head>
<body>
    <h1>Configure Camera</h1>
    <form action="{{ url_for('mako_camera.configure') }}" method="post">
        <!-- <label for="AcquisitionFrameRate"> Frame Rate:</label>
        <input type="number" name="AcquisitionFrameRate" id="AcquisitionFrameRate" value="{{AcquisitionFrameRate}}">
        <input type="submit" value="Save Configuration"> -->
        {% if failed_features %}
            {% for feature, message in failed_features.items() %}
            <p style="color: red;">{{ feature }}: {{ message }}</p>
            {% endfor %}
        {% elif failed_features is mapping and failed_features %}
            <p style="color: green;">Configuration saved successfully!</p>
        {% endif %}
        {% for item in cam_features %}
        {% set key = item["name"] %}
        {% set type_ = item["type"] %}
        {% set value = item["value"] %}
        {% set writeEnabled = item["access_mode"][1] %}
            <label for="{{key}}">{{key}}:</label>
            {% if type_ == "IntFeature" %}
                <input type="number" name="{{key}}" id="{{key}}" value="{{value}}" {% if not writeEnabled %}disabled{% endif %}>
                Limits: {{item["range"]}}
            {% elif type_ == "FloatFeature" %}
                <input type="number" name="{{key}}" id="{{key}}" value="{{value}}" step="any" {% if not writeEnabled %}disabled{% endif %}>
                Limits: {{item["range"]}}
            {% elif type_ == "BoolFeature" %}
                <input type="checkbox" name="{{key}}" id="{{key}}" {% if value %}checked{% endif %} {% if not writeEnabled %}disabled{% endif %}>
            {% elif type_ == "EnumFeature" %}
                <select name="{{key}}" id="{{key}}">
                    {% for option in item["available_entries"] %}
                        <option value="{{option}}" {% if option == value %}selected{% endif %}>{{option}}</option>
                    {% endfor %}
                </select>
            {% else %}
                <input type="text" name="{{key}}" id="{{key}}" value="{{value}}" {% if not writeEnabled %}disabled{% endif %}>
            {% endif %}
            <br>
        {% endfor %}
        <input type="submit" value="Save Configuration">
    </form>
</body>
</html>